# Jekyll configuration for Open SDG platform

# Doing the Quick start? Here are the settings to update during installation:
#
# Replace the baseurl with the name of this repository. For example, if the repository is named
# "my-site-repository", then update the baseurl like so:
# baseurl: "/my-site-repository"
baseurl: "/open-sdg-site-starter"
# The next line should be the URL of your data repository published site. To find this,
# go to your data repository in Github, and click "Settings", then scroll down to the
# "Github Pages" section. Copy/paste the link in the green section.
remote_data_prefix: "https://open-sdg.org/open-sdg-data-starter"
# In the next few items, replace "open-sdg" with the name of your GitHub
# organization, and "open-sdg-data-starter" with the name of your data repository.
# URL for the "Edit Data" button on indicators.
# That's enough for the Quick Start! The remaining settings can be configured later.

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@1.3.1

# Replace this title as needed.
title: general.site_title
url: ""
environment: staging

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE
